src_legacy/JLM/FollowBundle/Entity/Starter.php
<?php

namespace JLM\FollowBundle\Entity;

use JLM\FollowBundle\Model\StarterInterface;

abstract class Starter implements StarterInterface
{
    private $id;
    
    private $work;
    
    public function getId()
    {
        return $this->id;
    }
    
    final public function getWork()
    {
        $this->work = $this->getMyWork();
        
        return $this->work;
    }

    abstract protected function getMyWork();
}

src_legacy/JLM/FollowBundle/Entity/StarterIntervention.php
<?php

namespace JLM\FollowBundle\Entity;

use JLM\DailyBundle\Model\InterventionInterface;

class StarterIntervention extends Starter
{
    /**
     * @var InterventionInterface
     */
    private $intervention;
    
    public function __construct(InterventionInterface $intervention)
    {
        $this->setIntervention($intervention);
    }
    
    /**
     * @param InterventionInterface $intervention
     * @return self
     */
    public function setIntervention(InterventionInterface $intervention)
    {
        $this->intervention = $intervention;
        
        return $this;
    }
    
    /**
     * @return InterventionInterface
     */
    public function getIntervention()
    {
        return $this->intervention;
    }
    
    protected function getMyWork()
    {
        return $this->getIntervention()->getWork();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'Intervention du '.$this->getIntervention()->getLastDate()->format('d/m/Y');
    }
    
    /**
     * {@inheritdoc}
     */
    public function getBusiness()
    {
        return $this->getIntervention()->getDoor();
    }
    
    public function getAmount()
    {
        return 'Complet';
    }
    
    /**
     * {@inheritdoc}
     */
    public function getType()
    {
        return 'intervention';
    }
}

src_legacy/JLM/FollowBundle/Entity/StarterQuote.php
<?php

namespace JLM\FollowBundle\Entity;

use JLM\CommerceBundle\Model\QuoteVariantInterface;

class StarterQuote extends Starter
{
    /**
     * @var QuoteVariantInterface
     */
    private $variant;
    
    public function __construct(QuoteVariantInterface $variant)
    {
        $this->setVariant($variant);
    }
    
    /**
     * @param QuoteVariantInterface $variant
     * @return self
     */
    public function setVariant(QuoteVariantInterface $variant)
    {
        $this->variant = $variant;
        
        return $this;
    }
    
    /**
     * @return QuoteVariantInterface
     */
    public function getVariant()
    {
        return $this->variant;
    }
    
    protected function getMyWork()
    {
        return $this->getVariant()->getWork();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'Devis n°'.$this->getVariant()->getNumber();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getBusiness()
    {
        return $this->getVariant()->getDoor();
    }
    
    public function getAmount()
    {
        return $this->getVariant()->getTotalPrice();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getType()
    {
        return 'quote';
    }
}

src_legacy/JLM/FollowBundle/Entity/Thread.php
<?php

namespace JLM\FollowBundle\Entity;

use JLM\FollowBundle\Model\ThreadInterface;
use JLM\FollowBundle\Model\StarterInterface;
use JLM\CommerceBundle\Model\OrderInterface;
use JLM\DailyBundle\Model\WorkInterface;
use JLM\OfficeBundle\Entity\Order;

class Thread implements ThreadInterface
{
    const STATE_WAIT = 0;
    const STATE_READY = 1;
    const STATE_INPROGRESS = 2;
    const STATE_OK = 3;
    const STATE_CLOSED = 4;
    
    /**
     * @var int
     */
    private $id;
    
    /**
     * @var \DateTime
     */
    private $startDate;
    
    /**
     * @var StarterInterface
     */
    private $starter;
    
    /**
     * @var float
     */
    private $amount;
    
    /**
     * @var Work
     */
    private $work;
    
    /**
     * @var Order
     */
    private $order;
    
    /**
     * @var int
     */
    private $state = 0;
    
    public function __construct(StarterInterface $starter)
    {
        $this->setStartDate();
        $this->setStarter($starter);
    }
    
    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * @param StarterInterface $starter
     * @return self
     */
    public function setStarter(StarterInterface $starter)
    {
        $this->starter = $starter;
        $this->work = $this->starter->getWork();
        
        return $this;
    }
    
    /**
     * @return StarterInterface
     */
    public function getStarter()
    {
        return $this->starter;
    }
    
    /**
     * @return OrderInterface
     */
    public function getOrder()
    {
        $this->order = isset($this->order) ? $this->order : $this->getWork()->getOrder();
        
        return $this->order;
    }
    
    /**
     * @return WorkInterface
     */
    public function getWork()
    {
        $this->work = isset($this->work) ? $this->work : $this->getStarter()->getWork();
        
        return $this->work;
    }
    
    /**
     * @param \DateTime $date
     * @return self
     */
    public function setStartDate(\DateTime $date = null)
    {
        $this->startDate = ($date === null) ? new \DateTime : $date;
        
        return $this;
    }
    
    /**
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }
    
    public function getAmount()
    {
        $this->amount = isset($this->amount) ? $this->amount : $this->getStarter()->getAmount();
        
        return $this->amount;
    }
    
    public function getState()
    {
        $this->state = $this->defineState();
        
        return $this->state;
    }
    
    private function defineState()
    {
        if ($this->getWork() === null) {
            return self::STATE_CLOSED;
        }
        if ($this->getWork()->getBill() !== null || $this->getWork()->getExternalBill() !== null) {
            return self::STATE_CLOSED;
        }
        if ($this->getWork()->getClose() !== null) {
            return self::STATE_OK;
        }
        if ($this->getWork()->getFirstDate() !== null) {
            return self::STATE_INPROGRESS;
        }
        if (!$this->getOrder() instanceof Order || $this->getOrder()->getState() < 2) {
            return self::STATE_WAIT;
        }
        if ($this->getOrder()->getState() >= 2) {
            return self::STATE_READY;
        }
    }
}

src_legacy/JLM/FollowBundle/Controller/DefaultController.php
<?php

namespace JLM\FollowBundle\Controller;

use Doctrine\ORM\EntityManagerInterface;
use JLM\CoreBundle\Service\Paginator;
use JLM\FollowBundle\Entity\Thread;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @IsGranted("ROLE_OFFICE")
 */
class DefaultController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function indexAction(Paginator $paginator, Request $request)
    {
        return $this->render('@JLMFollow/Default/index.html.twig', $paginator->paginator($request, $this->entityManager->getRepository(Thread::class), [
            'type' => null,
            'sort' => '!date',
            'state' => null
        ]));
    }
    
    public function updateAction()
    {
        $threads = $this->entityManager->getRepository(Thread::class)->findAll();
        foreach ($threads as $thread) {
            $thread->getState();
            $thread->getAmount();
            $this->entityManager->persist($thread);
        }
        
        $this->entityManager->flush();
        
        return 'Mise à jour OK';
    }
}

src_legacy/JLM/FollowBundle/Resources/views/Default/index.html.twig
{% extends '@JLMCore/layout.html.twig' %}

{% block content %}
<h1>Suivi de commandes</h1>
<a class="btn btn-primary" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'type' : 'variant' })) }}">Devis</a>
<a class="btn btn-primary" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'type' : 'intervention' })) }}">Interventions</a>
<a class="btn btn-default" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'state' : 0 })) }}">Non traités</a>
<a class="btn btn-default" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'state' : 1 })) }}">Matériel prêt</a>
<a class="btn btn-default" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'state' : 2 })) }}">Travaux commencés</a>
<a class="btn btn-default" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'state' : 3 })) }}">Terminés</a>
<a class="btn btn-default" href="{{ path('jlm_follow_default_index',pagination.route_params|merge({ 'page':1, 'state' : 3 })) }}">Cloturé</a>
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Syndic</th>
      <th>Affaire</th>
      <th>Origine</th>
      <th>Montant</th>
      <th>Commande fournisseur</th>
      <th>Préparation matériel</th>
      <th>Début des travaux</th>
      <th>Fin des travaux</th>
      <th>Facturation</th>
    </tr>
  </thead>
  <tbody>
{% for thread in entities %}
    <tr class="
      {%- if thread.state == 0 -%}danger
      {%- elseif thread.state == 1 -%}warning
      {%- elseif thread.state == 2 -%}info
      {%- elseif thread.state == 3 -%}success
      {%- elseif thread.state == 4 -%}success
      {%- endif -%}
    ">
      <td>{{ thread.startDate|date('d/m/Y') }}</td>
      <td>{% if thread.starter.business %}{{ thread.starter.business.manager|nl2br }}{% endif %}</td>
      <td>{% if thread.starter.business %}
        {%- if thread.starter.business.stopped -%}
        <span class="label label-important">Mise à l'arrêt</span><br>
        {%- endif -%}
        {{ thread.starter.business|nl2br }}{% endif %}
      </td>
      <td>
      	{%- if thread.starter.type == 'quote' -%}
      		<a href="{{ path('quote_show', {'id':thread.starter.variant.quote.id}) }}" data-toggle="tooltip" title="{{ thread.starter.variant.intro }}">
      	{%- elseif thread.starter.type == 'intervention' -%}
      	    <a data-toggle="tooltip" title="{{ thread.starter.intervention.rest }}">
      	{%- endif -%}
      	{{ thread.starter.name }}</a></td>
      <td>{{ thread.amount|number_format(2,',',' ') }}</td>
      <td>
        {% if thread.order and thread.state >= 0 %}
          <a href="{{ path('order_show', {'id': thread.order.id }) }}">{{ thread.order.creation|date('d/m/Y') }}</a>
        {% else %}
          <a href="{{ path('order_new', {'id': thread.work.id }) }}" class="btn btn-small">Créer la fiche travaux</a>
        {% endif %}
      </td>
      <td>{% if thread.order and thread.state >= 1 %}{{ thread.order.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 2 %}<a href="{{ path('work_show', {'id': thread.work.id }) }}">{{ thread.work.firstDate|date('d/m/Y') }}</a>{% endif %}</td>
      <td>{% if thread.state >= 3 %}{{ thread.work.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 4 %}
          {%- if thread.work.bill is not null -%}
      		<a href="{{ path('bill_show', { 'id':thread.work.bill.id }) }}">{{ thread.work.bill.number }}</a>
      	  {%- else -%}
      	  {{ thread.work.externalBill }}
      	  {%- endif -%}
      	{%- endif -%}
      </td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% include '@JLMCore/pagination.html.twig' %}
{% endblock %}

{% block pagination %}{% endblock %}

{% block javascripts_script %}
{{ parent() }}
$('a').tooltip({'placement':'right'});
{% endblock %}

src_legacy/JLM/FollowBundle/Resources/views/Default/intervention.html.twig
{% extends '@JLMCore/layout.html.twig' %}

{% block content %}
<h1>Suivi de commandes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Syndic</th>
      <th>Affaire</th>
      <th>Origine</th>
      <th>Montant</th>
      <th>Commande fournisseur</th>
      <th>Préparation matériel</th>
      <th>Début des travaux</th>
      <th>Fin des travaux</th>
      <th>Facturation</th>
    </tr>
  </thead>
  <tbody>
{% for thread in threads %}
  {%- if thread.starter.type == 'intervention' -%}
    <tr class="
      {%- if thread.state == 0 -%}danger
      {%- elseif thread.state == 1 -%}warning
      {%- elseif thread.state == 2 -%}info
      {%- elseif thread.state == 3 -%}success
      {%- elseif thread.state == 4 -%}success
      {%- endif -%}
    ">
      <td>{{ thread.startDate|date('d/m/Y') }}</td>
      <td>{{ thread.starter.business.manager|nl2br }}</td>
      <td>
        {%- if thread.starter.business.stopped -%}
        <span class="label label-important">Mise à l'arrêt</span><br>
        {%- endif -%}
        {{ thread.starter.business|nl2br }}
      </td>
      <td>
      	{%- if thread.starter.type == 'quote' -%}
      		<a href="{{ path('quote_show', {'id':thread.starter.variant.quote.id}) }}" data-toggle="tooltip" title="{{ thread.starter.variant.intro }}">
      	{%- elseif thread.starter.type == 'intervention' -%}
      	    <a data-toggle="tooltip" title="{{ thread.starter.intervention.rest }}">
      	{%- endif -%}
      	{{ thread.starter.name }}</a></td>
      <td>{{ thread.amount|number_format(2,',',' ') }}</td>
      <td>
        {% if thread.order and thread.state >= 0 %}
          <a href="{{ path('order_show', {'id': thread.order.id }) }}">{{ thread.order.creation|date('d/m/Y') }}</a>
        {% else %}
          <a href="{{ path('order_new', {'id': thread.work.id }) }}" class="btn btn-small">Créer la fiche travaux</a>
        {% endif %}
      </td>
      <td>{% if thread.order and thread.state >= 1 %}{{ thread.order.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 2 %}<a href="{{ path('work_show', {'id': thread.work.id }) }}">{{ thread.work.firstDate|date('d/m/Y') }}</a>{% endif %}</td>
      <td>{% if thread.state >= 3 %}{{ thread.work.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 4 %}
          {%- if thread.work.bill is not null -%}
      		<a href="{{ path('bill_show', { 'id':thread.work.bill.id }) }}">{{ thread.work.bill.number }}</a>
      	  {%- else -%}
      	  {{ thread.work.externalBill }}
      	  {%- endif -%}
      	{%- endif -%}
      </td>
    </tr>
    {% endif %}
{% endfor %}
  </tbody>
</table>
{% endblock %}

{% block javascripts_script %}
{{ parent() }}
$('a').tooltip({'placement':'right'});
{% endblock %}

src_legacy/JLM/FollowBundle/Resources/views/Default/quote.html.twig
{% extends '@JLMCore/layout.html.twig' %}

{% block content %}
<h1>Suivi de commandes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Syndic</th>
      <th>Affaire</th>
      <th>Origine</th>
      <th>Montant</th>
      <th>Commande fournisseur</th>
      <th>Préparation matériel</th>
      <th>Début des travaux</th>
      <th>Fin des travaux</th>
      <th>Facturation</th>
    </tr>
  </thead>
  <tbody>
{% for thread in threads %}
  {%- if thread.starter.type == 'quote' -%}
    <tr class="
      {%- if thread.state == 0 -%}danger
      {%- elseif thread.state == 1 -%}warning
      {%- elseif thread.state == 2 -%}info
      {%- elseif thread.state == 3 -%}success
      {%- elseif thread.state == 4 -%}success
      {%- endif -%}
    ">
      <td>{{ thread.startDate|date('d/m/Y') }}</td>
      <td>{{ thread.starter.business.manager|nl2br }}</td>
      <td>
        {%- if thread.starter.business.stopped -%}
        <span class="label label-important">Mise à l'arrêt</span><br>
        {%- endif -%}
        {{ thread.starter.business|nl2br }}
      </td>
      <td>
      	{%- if thread.starter.type == 'quote' -%}
      		<a href="{{ path('quote_show', {'id':thread.starter.variant.quote.id}) }}" data-toggle="tooltip" title="{{ thread.starter.variant.intro }}">
      	{%- elseif thread.starter.type == 'intervention' -%}
      	    <a data-toggle="tooltip" title="{{ thread.starter.intervention.rest }}">
      	{%- endif -%}
      	{{ thread.starter.name }}</a></td>
      <td>{{ thread.amount|number_format(2,',',' ') }}</td>
      <td>
        {% if thread.order and thread.state >= 0 %}
          <a href="{{ path('order_show', {'id': thread.order.id }) }}">{{ thread.order.creation|date('d/m/Y') }}</a>
        {% else %}
          <a href="{{ path('order_new', {'id': thread.work.id }) }}" class="btn btn-small">Créer la fiche travaux</a>
        {% endif %}
      </td>
      <td>{% if thread.order and thread.state >= 1 %}{{ thread.order.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 2 %}<a href="{{ path('work_show', {'id': thread.work.id }) }}">{{ thread.work.firstDate|date('d/m/Y') }}</a>{% endif %}</td>
      <td>{% if thread.state >= 3 %}{{ thread.work.close|date('d/m/Y') }}{% endif %}</td>
      <td>{% if thread.state >= 4 %}
          {%- if thread.work.bill is not null -%}
      		<a href="{{ path('bill_show', { 'id':thread.work.bill.id }) }}">{{ thread.work.bill.number }}</a>
      	  {%- else -%}
      	  {{ thread.work.externalBill }}
      	  {%- endif -%}
      	{%- endif -%}
      </td>
    </tr>
    {% endif %}
{% endfor %}
  </tbody>
</table>
{% endblock %}

{% block javascripts_script %}
{{ parent() }}
$('a').tooltip({'placement':'right'});
{% endblock %}