src_legacy/JLM/TransmitterBundle/Entity/Attribution.php
<?php

namespace JLM\TransmitterBundle\Entity;

use JLM\CommerceBundle\Model\BillInterface;
use JLM\TransmitterBundle\Model\AttributionInterface;
use JLM\TransmitterBundle\Model\TransmitterInterface;

/**
 * Attribution
 */
class Attribution implements AttributionInterface
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $creation;

    /**
     * @var string
     */
    private $contact;

    /**
     * @var boolean
     */
    private $individual;

    /**
     * @var ArrayCollection
     */
    private $transmitters;
    
    /**
     * @var AskTransmitter
     */
    private $ask;
    
    /**
     * @var Bill
     */
    private $bill;
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set creation
     *
     * @param \DateTime $creation
     * @return Attribution
     */
    public function setCreation($creation)
    {
        $this->creation = $creation;
    
        return $this;
    }

    /**
     * Get creation
     *
     * @return \DateTime
     */
    public function getCreation()
    {
        return $this->creation;
    }

    /**
     * Set contact
     *
     * @param string $contact
     * @return Attribution
     */
    public function setContact($contact)
    {
        $this->contact = $contact;
    
        return $this;
    }

    /**
     * Get contact
     *
     * @return string
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * Set individual
     *
     * @param boolean $individual
     * @return Attribution
     */
    public function setIndividual($individual)
    {
        $this->individual = $individual;
    
        return $this;
    }

    /**
     * Get individual
     *
     * @return boolean
     */
    public function getIndividual()
    {
        return $this->individual;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->transmitters = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add transmitters
     *
     * @param \JLM\TransmitterBundle\Entity\Transmitter $transmitters
     * @return Attribution
     */
    public function addTransmitter(TransmitterInterface $transmitters)
    {
        $this->transmitters[] = $transmitters;
    
        return $this;
    }

    /**
     * Remove transmitters
     *
     * @param TransmitterInterface $transmitters
     */
    public function removeTransmitter(TransmitterInterface $transmitters)
    {
        $this->transmitters->removeElement($transmitters);
    }

    /**
     * Get transmitters
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTransmitters()
    {
        return $this->transmitters;
    }

    /**
     * Set ask
     *
     * @param Ask $ask
     * @return TransmitterAttribution
     */
    public function setAsk(Ask $ask = null)
    {
        $this->ask = $ask;
    
        return $this;
    }

    /**
     * Get ask
     *
     * @return Ask
     */
    public function getAsk()
    {
        return $this->ask;
    }

    /**
     * Set bill
     *
     * @param BillInterface $bill
     * @return Attribution
     */
    public function setBill(BillInterface $bill = null)
    {
        $this->bill = $bill;
    
        return $this;
    }

    /**
     * Get bill
     *
     * @return BillInterface
     */
    public function getBill()
    {
        return $this->bill;
    }
    
    /**
     * Get Site
     *
     * @return \JLM\ModelBundel\Entity\Site
     */
    public function getSite()
    {
        return $this->getAsk()->getSite();
    }
}

src_legacy/JLM/TransmitterBundle/Form/Type/AttributionType.php
<?php

namespace JLM\TransmitterBundle\Form\Type;

use JLM\ModelBundle\Form\Type\DatepickerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use JLM\TransmitterBundle\Entity\Attribution;

class AttributionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ask', AskHiddenType::class)
            ->add('creation', DatepickerType::class, ['label'=>'Date'])
            ->add('contact')
            ->add('individual', null, ['label'=>'Particulier','required'=>false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attribution::class
        ]);
    }

    public function getBlockPrefix(): string
    {
        return 'jlm_transmitterbundle_attributiontype';
    }
}

src_legacy/JLM/TransmitterBundle/Controller/AttributionController.php
<?php

namespace JLM\TransmitterBundle\Controller;

use Doctrine\ORM\EntityManagerInterface;
use JLM\CommerceBundle\Entity\EarlyPaymentModel;
use JLM\CommerceBundle\Entity\PenaltyModel;
use JLM\CommerceBundle\Entity\PropertyModel;
use JLM\CommerceBundle\Entity\VAT;
use JLM\CommerceBundle\Factory\BillFactory;
use JLM\CoreBundle\Response\PdfResponse;
use JLM\CoreBundle\Service\Paginator;
use JLM\ProductBundle\Entity\Product;
use JLM\TransmitterBundle\Builder\AttributionBillBuilder;
use JLM\TransmitterBundle\Entity\Attribution;
use JLM\TransmitterBundle\Entity\Ask;
use JLM\TransmitterBundle\Form\Type\AttributionType;
use JLM\TransmitterBundle\Pdf\AttributionCourrier;
use JLM\TransmitterBundle\Pdf\AttributionList;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/attribution")
 * @IsGranted("ROLE_OFFICE")
 */
class AttributionController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Lists all Attribution entities.
     *
     * @Route("/", name="transmitter_attribution")
     */
    public function indexAction(Paginator $paginator, Request $request)
    {
        return $this->render('@JLMTransmitter/Attribution/index.html.twig', $paginator->paginator(
            $request,
            $this->entityManager->getRepository(Attribution::class),
            ['sort' => '!date']
        ));
    }

    /**
     * Finds and displays a Attribution entity.
     *
     * @Route("/{id}/show", name="transmitter_attribution_show")
     */
    public function showAction(Attribution $entity)
    {
        return $this->render('@JLMTransmitter/Attribution/show.html.twig', [
            'entity' => $entity,
        ]);
    }

    /**
     * Displays a form to create a new Attribution entity.
     *
     * @Route("/new/{id}", name="transmitter_attribution_new")
     */
    public function newAction(Ask $ask)
    {
        $entity = new Attribution();
        $entity->setCreation(new \DateTime);
        $entity->setAsk($ask);
        $form = $this->createForm(AttributionType::class, $entity);

        return $this->render('@JLMTransmitter/Attribution/new.html.twig', [
            'entity' => $entity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Creates a new Attribution entity.
     *
     * @Route("/create", name="transmitter_attribution_create", methods={"POST"})
     */
    public function createAction(Request $request)
    {
        $entity = new Attribution();
        $form = $this->createForm(AttributionType::class, $entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($entity);
            $this->entityManager->flush();

            return $this->redirectToRoute('transmitter_attribution_show', ['id' => $entity->getId()]);
        }

        return $this->render('@JLMTransmitter/Attribution/new.html.twig', [
            'entity' => $entity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Displays a form to edit an existing Attribution entity.
     *
     * @Route("/{id}/edit", name="transmitter_attribution_edit")
     */
    public function editAction(Attribution $entity)
    {
        $editForm = $this->createForm(AttributionType::class, $entity);

        return $this->render('@JLMTransmitter/Attribution/edit.html.twig', [
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
        ]);
    }

    /**
     * Edits an existing Attribution entity.
     *
     * @Route("/{id}/update", name="transmitter_attribution_update", methods={"POST"})
     */
    public function updateAction(Request $request, Attribution $entity)
    {
        $editForm = $this->createForm(AttributionType::class, $entity);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->entityManager->persist($entity);
            $this->entityManager->flush();

            return $this->redirectToRoute('transmitter_attribution_show', ['id' => $entity->getId()]);
        }

        return $this->render('@JLMTransmitter/Attribution/edit.html.twig', [
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
        ]);
    }

    /**
     * Imprime la liste d'attribution
     *
     * @Route("/{id}/printlist", name="transmitter_attribution_printlist")
     */
    public function printlistAction(Attribution $entity)
    {
        // Retrier les bips par Groupe puis par numéro
        $transmitters = $entity->getTransmitters();
        $resort = [];
        foreach ($transmitters as $transmitter) {
            $index = $transmitter->getUserGroup()->getName();
            if (!isset($resort[$index])) {
                $resort[$index] = [];
            }
            $resort[$index][] = $transmitter;
        }

        $final = array_merge([], ...$resort);

        return new PdfResponse('attribution-' . $entity->getId() . '.pdf', AttributionList::get($entity, $final, true));
    }

    /**
     * Imprime le courrier
     *
     * @Route("/{id}/printcourrier", name="transmitter_attribution_printcourrier")
     */
    public function printcourrierAction(Attribution $entity)
    {
        return new PdfResponse(
            'attribution-courrier-' . $entity->getId() . '.pdf',
            AttributionCourrier::get($entity)
        );
    }

    /**
     * Generate bill
     *
     * @Route("/{id}/bill", name="transmitter_attribution_bill")
     */
    public function billAction(Attribution $entity)
    {
        if ($entity->getBill() !== null) {
            return ($this->redirectToRoute('bill_edit', ['id' => $entity->getBill()->getId()]));
        }
        // @todo trouver un autre solution que le codage brut
        $options = [
            'port' => $this->entityManager->getRepository(Product::class)->find(134),
            'earlyPayment' => (string) $this->entityManager->getRepository(EarlyPaymentModel::class)->find(1),
            'penalty' => (string) $this->entityManager->getRepository(PenaltyModel::class)->find(1),
            'property' => (string) $this->entityManager->getRepository(PropertyModel::class)->find(1),
        ];
        $bill = BillFactory::create(new AttributionBillBuilder(
            $entity,
            $this->entityManager->getRepository(VAT::class)->find(1)->getRate(),
            $options
        ));
        $this->entityManager->persist($bill);
        $entity->setBill($bill);
        $this->entityManager->persist($entity);
        $this->entityManager->flush();

        return $this->redirectToRoute('bill_edit', ['id' => $bill->getId()]);
    }
}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/edit.html.twig
{% extends '@JLMTransmitter/Ask/layout.html.twig' %}

{% block content %}
<h1>Edition d'attribution d'émetteurs</h1>
{% if form_errors(edit_form) %}
<div class="alert">{{ form_errors(edit_form) }}</div>
{% endif %}
{{ form_start(edit_form, {'action': path('transmitter_attribution_update', { 'id': entity.id }), 'attr': {'class': 'form-horizontal'}}) }}
	<filedset>
    {{ form_widget(edit_form) }}
	    <div class="form-actions">
	    	<button type="submit" class="btn btn-primary">Enregistrer</button>
	    </div>
    </filedset>
{{ form_end(edit_form) }}
{% endblock %}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/index.html.twig
{% extends '@JLMTransmitter/Attribution/layout.html.twig' %}

{% block content %}
<h1>Attributions d'émetteurs</h1>
<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Affaire</th>
            <th>Nb de bips</th>
            <th>Contact</th>
            <th>Particulier</th>
            <th>Facturation</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td>{% if entity.creation %}{{ entity.creation|date('d/m/Y') }}{% endif %}</td>
            <td><a href="{{ path('transmitter_attribution_show', { 'id': entity.id }) }}">{{ entity.ask.site.address|default('') |nl2br }}</a></td>
            <td>{{ entity.transmitters|length }}</td>
            <td>{{ entity.contact }}</td>
            <td>{% if entity.individual %}{{ 'ok'|icon }}{% endif %}</td>
            <td>
            	{% if entity.bill %}
            	{% include '@JLMCommerce/Bill/statelabel.html.twig' with {'state': entity.bill.state} %}
            	<br><a href="{{ path('bill_show', { 'id': entity.bill.id }) }}">{{ entity.bill.number }}</a>
            	{% else %}
            	Non facturé
            	{% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% include '@JLMCore/pagination.html.twig' %}
{% endblock %}

{% block pagination %}{% endblock %}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/layout.html.twig
{% extends '@JLMTransmitter/layout.html.twig' %}
{% block sidebar %}
<ul class="nav nav-list  affix">
	<li><h4>Attributions d'émetteurs</h4></li>
	<li>{{ form(search.form, { 'action': path('transmitter_search') }) }}
	<li><a href="{{ path('transmitter_ask_new') }}">{{ 'plus-sign'|icon }} Nouvelle commandes d'émetteurs</a></li>
	<li class="divider"></li>
	<li class="nav-header">États</li>
	{% include '@JLMTransmitter/Attribution/sidebar.html.twig' %}
</ul>
{% endblock sidebar %}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/new.html.twig
{% extends '@JLMTransmitter/Ask/layout.html.twig' %}

{% block content %}
<h1>Nouvelle attribution d'émetteurs</h1>
{% if form_errors(form) %}
<div class="alert">{{ form_errors(form) }}</div>
{% endif %}
{{ form_start(form, {'action': path('transmitter_attribution_create'), 'attr': {'class': 'form-horizontal'}}) }}
	<fieldset>
    {{ form_widget(form) }}
	    <div class="form-actions">
	    	<button type="submit" class="btn btn-primary">Enregistrer</button>
	    </div>
    </fieldset>
{{ form_end(form) }}
{% endblock %}

{% block javascripts_script %}
{{ parent() }}
$("#jlm_transmitterbundle_attributiontype_contact")
				.autocomplete({
					source: function(request,response){
						request.term = {{ entity.ask.site.doors.0.id }};
						request.repository = 'JLMModelBundle:SiteContact';
						return $.post(
								'{{ path('autocomplete') }}',
								request,
								function( data ) { response( data ); },
								'json'
						);
					}
				, select: function (event, ui) {
					$(this).val(ui.item.name);
					return false;
				}
			});
{% endblock %}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/show.html.twig
{% extends '@JLMTransmitter/Ask/layout.html.twig' %}

{% block content %}
<h1>Attribution d'émetteurs</h1>
<div class="row-fluid">
<div class="span6">
<dl class="dl-horizontal">
	<dt>Date</dt>
	<dd>{{ entity.creation|date('d/m/Y') }}</dd>
	<dt>Contact</dt>
    <dd>{{ entity.contact }}{% if entity.individual %} (particulier){% endif %}</dd>
    <dt>Affaire</dt>
    <dd>{{ entity.ask.site.address.street | nl2br }}</dd>
    <dd><strong>{{ entity.ask.site.address.city.name | upper }}</strong> <small>{{ entity.ask.site.address.city.zip }}</small></dd>
    <dd><a href="{{ path('transmitter_site_printlist',{'id':entity.ask.site.id}) }}" class="btn btn-info btn-mini">{{ 'print'|icon(true) }} Imprimer la liste complète</a>
    <dt>Demande</dt>
    <dd>{{ entity.ask.ask | nl2br }}</dd>
</dl>
</div>
<div class="span6">
<h4>Groupes utilisateurs</h4>
<ul>
	{% for userGroup in entity.ask.site.userGroups %}
		{% include '@JLMTransmitter/UserGroup/list_li.html.twig' with {'userGroup':userGroup} %}
	{% endfor %}
	</ul>
	<a href="{{ path('transmitter_usergroup_new', {'id': entity.ask.site.id}) }}"  role="button" class="btn btn-success btn-small usergroup-new">{{ 'plus-sign'|icon(true) }} Ajouter un groupe utilisateur</a>
</div>
</div>
<div class="form-actions">
	<a href="{{ path('transmitter_attribution_edit', { 'id': entity.id }) }}" class="btn btn-warning">{{ 'pencil'|icon(true) }} Editer</a>
	<a href="{{ path('transmitter_new', { 'id': entity.id }) }}" role="button" class="btn btn-success transmitter-new">{{ 'plus-sign'|icon(true) }} Ajouter un émetteur</a>
	<a href="{{ path('transmitter_series_new', { 'id': entity.id }) }}" role="button" class="btn btn-success series-new">{{ 'plus-sign'|icon(true) }} Ajouter une suite d'émetteurs</a>
	<a href="{{ path('transmitter_replacement_new', { 'id': entity.id }) }}" role="button" class="btn btn-primary replacement-new">{{ 'refresh'|icon(true) }} Remplacement d'émetteurs</a>
	<a href="{{ path('transmitter_attribution_printlist', { 'id': entity.id }) }}" role="button" class="btn btn-info">{{ 'print'|icon(true) }} Imprimer la liste</a>
	<a href="{{ path('transmitter_attribution_printcourrier', { 'id': entity.id }) }}" role="button" class="btn btn-info">{{ 'print'|icon(true) }} Imprimer le courrier</a>
	{% if entity.bill %}
	<a href="{{ path('bill_print', {'id': entity.bill.id}) }}" role="button" class="btn btn-primary">{{ 'print'|icon(true) }} Facture</a>
	{% else %}
	<a href="{{ path('bill_new', { 'attribution': entity.id }) }}" role="button" class="btn btn-primary">{{ 'print'|icon(true) }} Facturer</a>
	{% endif %}
</div>
{% if entity.transmitters|length > 0 %}
<h3></h3>
	{% include '@JLMTransmitter/Transmitter/table_row.html.twig' with {'transmitters':entity.transmitters} %}
{% else %}
<h3>Pas d'émetteur attribué</h3>
{% endif %}
{% endblock %}

{% block javascripts_script %}
{{ parent() }}
$("a").tooltip();
$(".transmitter-new").formModal({closure: function(){location.reload();}});
$(".transmitter-edit").formModal({closure: function(){location.reload();}});
$(".usergroup-new, .usergroup-edit").formModal({closure: function(){location.reload();}});
$(".series-new").formModal({closure: function(){location.reload();}});
$(".replacement-new").formModal({closure: function(){location.reload();}});
{% endblock %}

src_legacy/JLM/TransmitterBundle/Resources/views/Attribution/sidebar.html.twig
<li><a href="{{ path('transmitter_attribution') }}"><span class="badge badge-inverse">{{ transmitterattributioncount.all }}</span> Toutes</a></li>